<?php


namespace Handler\Novel;


use Handler\Dao\ParaCommentDao;
use Handler\Novel\Comment\AbComment;

class CommentParaCreate extends AbCommentService
{

    public function __construct(AbComment $comment)
    {
        parent::__construct($comment);
    }

    public function execute()
    {
        $this->comment->setCommentDao(new ParaCommentDao());

        parent::execute(); // TODO: Change the autogenerated stub
    }

}